In [1]:
import torch
import torch.nn.functional as F
import numpy as np

from ssgd import StreamingSGD

In [2]:
torch.set_printoptions(precision=10)

In [3]:
torch.manual_seed(9)

# Model definition

A StreamingSGD compatible model now needs to be able to "detach" layers as well as gather input/output and gradients. It also needs a list of layers. See below for implementation example. In the future we want to implement this using PyTorch hooks and modules.

In [4]:
class ExampleNet(torch.nn.Module):
    def __init__(self):
        super(ExampleNet, self).__init__()
        
        self.input_layer = torch.nn.Conv2d(3, 3, kernel_size=3)
        self.layers = [self.input_layer]

        for i in range(5):  # use 9 for 8194 x 8194 images
            self.add_block(i)
        
        final_conv5 = torch.nn.Conv2d(3, 1, kernel_size=10)
        self.add_module("final", final_conv5)
        
        self.layers.extend([final_conv5])
        
    def add_block(self, i):
        conv1 = torch.nn.Conv2d(3, 3, kernel_size=3)
        conv2 = torch.nn.Conv2d(3, 3, kernel_size=3)
        conv3 = torch.nn.Conv2d(3, 3, kernel_size=3)
        maxpool = torch.nn.MaxPool2d(2, stride=2)
        
        self.add_module("conv1-" + str(i), conv1)
        self.add_module("conv2-" + str(i), conv2)
        self.add_module("conv3-" + str(i), conv3)
        self.add_module("maxpool-" + str(i), maxpool)

        self.layers.extend([conv1, conv2, conv3, maxpool])

    def forward(self, x, stop_at_layer=None, start_at_layer=None):
        stop_index, start_index = -1, 0
        for i, (name, layer) in enumerate(self.named_modules()):
            if name == stop_at_layer:
                stop_index = i
            if name == start_at_layer:
                start_index = i
        
        for i, layer in enumerate(self.layers[start_index:]):
            if i == stop_index:
                break
                
            if i + 1 == len(self.layers[start_index:]):
                x = layer(x)
                x = x.view(-1, 1)
                x = F.sigmoid(x)
            else:
                x = F.relu(layer(x))

        return x

model = ExampleNet()
# model = model.double()

Weight initialization; we use positive values to generate large gradients, better for testing if final gradients are correct.

In [5]:
for i, layer in enumerate(model.modules()):
    if isinstance(layer, torch.nn.Conv2d):
        layer.weight.data *= 2.5
        layer.bias.data.zero_()

In [6]:
print(model)

ExampleNet(
  (input_layer): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv1-0): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv2-0): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv3-0): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (maxpool-0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv1-1): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv2-1): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv3-1): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (maxpool-1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv1-2): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv2-2): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv3-2): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (maxpool-2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv1-3): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (conv2-3): Conv2d(3, 3, kernel_size=(3, 3

# Configurations

In [7]:
stop_layer = 'conv1-3'  # use 'conv3-4' for 8194x8194 images
img_size = 514  # try 8194, see last segment for details

cuda = False # execute this notebook on the GPU
verbose = False  # enable / disable logging
divide_in = 8  # tip: use 25 for 8194x8194 when memory constraint

# Configure streaming SGD

In [8]:
if cuda:
    model.cuda()

In [9]:
sCNN = StreamingSGD(model, stream_to_layer=stop_layer, 
               input_shape=(1, 3, img_size, img_size), 
               divide_in=divide_in, 
               cuda=cuda, 
               verbose=verbose)


# Generate random image and fake label

In the current implementation the whole image needs to be able to fit in memory (RAM).

In [10]:
image = torch.FloatTensor(3, img_size, img_size).normal_(0, 1)
target = torch.FloatTensor(1, 1).fill_(0)

# image = image.double()
# target = target.double()

if cuda:
    target = target.cuda()
    image = image.cuda()

In [11]:
criterion = torch.nn.BCELoss()

# Run through network using streaming

In [12]:
sCNN.start_batch()

In [13]:
output, feature_map = sCNN.forward(image); output

tensor([[0.5723423362]])

In [14]:
loss = criterion(output, target); loss

tensor(0.8494322300)

In [15]:
full_gradients = sCNN.backward(image, feature_map, loss)

Few more random images to test mini-batch workings:

In [16]:
image2 = torch.FloatTensor(3, img_size, img_size).normal_(0, 1)
image2 = image2.cuda() if cuda else image2
    
output, feature_map = sCNN.forward(image2);
loss2 = criterion(output, target);
sCNN.backward(image2, feature_map, loss2)
output

tensor([[0.4111766517]])

In [17]:
image3 = torch.FloatTensor(3, img_size, img_size).normal_(0, 1)
image3 = image3.cuda() if cuda else image3
    
output, feature_map = sCNN.forward(image3)
loss3 = criterion(output, target)
sCNN.backward(image3, feature_map, loss3)
output

tensor([[0.4662562311]])

In [18]:
sCNN.end_batch()

"Everything reconstructed" means that all gradients were reconstructed succesfully!

Save the gradients of the conv2d layer to compare with normal SGD:

In [19]:
streaming_conv_gradients = []

for i, layer in enumerate(model.layers):
    if isinstance(layer, torch.nn.Conv2d):
        if layer.weight.grad is not None:
            streaming_conv_gradients.append(layer.weight.grad.clone()) 

# Compare to normal SGD

Reset the gradients and perform a normal for backward pass.

In [20]:
for i, layer in enumerate(model.layers):
    if isinstance(layer, torch.nn.Conv2d):
        if layer.weight.grad is not None:
            layer.weight.grad.data.zero_()
            layer.bias.grad.data.zero_()

This output should be the same as the streaming SGD output, if so the loss will also be the same:

In [21]:
output = model(torch.stack((image, image2, image3))); output

tensor([[0.5723423362],
        [0.4111766517],
        [0.4662562311]])

In [22]:
loss = criterion(output, torch.stack((target[0], target[0], target[0]))); loss

tensor(0.6689669490)

In [23]:
loss.backward()

# Compare the gradients of the conv2d layers

Save the gradients of the conv2d layer to compare with normal SGD:

In [24]:
normal_conv_gradients = []
j = 0
for i, layer in enumerate(model.layers):
    if isinstance(layer, torch.nn.Conv2d):
        if layer.weight.grad is not None:
            normal_conv_gradients.append(layer.weight.grad) 
            j += 1

In [25]:
for i in range(len(streaming_conv_gradients)):
    print("Conv layer", i, "\taverage gradient size:", float(torch.mean(torch.abs(streaming_conv_gradients[i].data))))

Conv layer 0 	average gradient size: 0.41282185912132263
Conv layer 1 	average gradient size: 0.3332231938838959
Conv layer 2 	average gradient size: 0.21916089951992035
Conv layer 3 	average gradient size: 0.18337439000606537
Conv layer 4 	average gradient size: 0.1960972398519516
Conv layer 5 	average gradient size: 0.1934003382921219
Conv layer 6 	average gradient size: 0.11949021369218826
Conv layer 7 	average gradient size: 0.11961273849010468
Conv layer 8 	average gradient size: 0.08668350428342819
Conv layer 9 	average gradient size: 0.08268420398235321
Conv layer 10 	average gradient size: 0.08335243165493011
Conv layer 11 	average gradient size: 0.06348138302564621
Conv layer 12 	average gradient size: 0.08306340128183365
Conv layer 13 	average gradient size: 0.019830981269478798
Conv layer 14 	average gradient size: 0.0373382531106472
Conv layer 15 	average gradient size: 0.016475338488817215
Conv layer 16 	average gradient size: 0.12455208599567413


In [26]:
for i in range(len(streaming_conv_gradients)):
    max_diff = torch.max(torch.abs(streaming_conv_gradients[i].data - 
                         normal_conv_gradients[i].data))
    print("Conv layer", i, "\tmax difference between gradients:", float(max_diff))

Conv layer 0 	max difference between gradients: 2.6226043701171875e-06
Conv layer 1 	max difference between gradients: 2.3245811462402344e-06
Conv layer 2 	max difference between gradients: 1.9073486328125e-06
Conv layer 3 	max difference between gradients: 7.152557373046875e-07
Conv layer 4 	max difference between gradients: 6.556510925292969e-07
Conv layer 5 	max difference between gradients: 6.556510925292969e-07
Conv layer 6 	max difference between gradients: 8.344650268554688e-07
Conv layer 7 	max difference between gradients: 9.238719940185547e-07
Conv layer 8 	max difference between gradients: 5.438923835754395e-07
Conv layer 9 	max difference between gradients: 3.5762786865234375e-07
Conv layer 10 	max difference between gradients: 2.5331974029541016e-07
Conv layer 11 	max difference between gradients: 3.725290298461914e-07
Conv layer 12 	max difference between gradients: 5.364418029785156e-07
Conv layer 13 	max difference between gradients: 1.4901161193847656e-07
Conv layer 14

As you can see the difference of the gradients of the conv2d layers between the methods is (almost) numerically equivalent. The small differences are because of loss of significance with the floating points calculations. 

---

# Things to try:

* Use doubles instead of floats to reduce the difference (use model.double() and image_var.double())
* Make the image bigger than would fit on a GPU 
    - e.g. 8194x8194, make sure to add 3 more blocks in the model (see comments)
* If you want you can compare the reconstructed input gradients of each layer: 
    - pass fill_gradient=True in backward() function
    - compare full_gradients with self.model.gradients after the full model backward pass.
* For testing purposes the number of filters is small in this notebook, try increasing them